import prisma from '../config/prisma.js';
import logger from '../utils/logger.js';
import { generateQuestionPaper } from '../services/adaptiveEngineService.js';

export const generatePaper = async (req, res) => {
  try {
    const role = String(req.user.role || '').toUpperCase();
    const {
      subjectCode,
      totalMarks,
      examType,
      adaptiveEnabled = true,
      seed,
      targetStudentUserId,
      includeQuestionText = true,
      excludeLastNPapers,
      recentAttemptDays,
    } = req.body;

    // Resolve target student mode
    let effectiveTargetStudentUserId = null;
    if (role === 'STUDENT') {
      effectiveTargetStudentUserId = req.user.id;
    } else if (targetStudentUserId) {
      effectiveTargetStudentUserId = targetStudentUserId;
    }

    const result = await generateQuestionPaper({
      actorUserId: req.user.id,
      actorRole: role,
      subjectCode,
      totalMarks,
      examType,
      adaptiveEnabled,
      seed,
      targetStudentUserId: effectiveTargetStudentUserId,
      includeQuestionText: role === 'STUDENT' ? true : Boolean(includeQuestionText),
      excludeLastNPapers,
      recentAttemptDays,
    });

    logger.info(`[ADAPTIVE_ENGINE] Paper generated by ${req.user.email} (${role})`, {
      subjectCode,
      totalMarks,
      examType,
      paperId: result?.exam_metadata?.paper_id,
    });

    return res.success(result, 'Question paper generated successfully.', 201);
  } catch (err) {
    return res.error(err.message, 400);
  }
};

export const listMyPapers = async (req, res) => {
  try {
    const role = String(req.user.role || '').toUpperCase();
    const limit = Math.min(Math.max(Number(req.query.limit) || 10, 1), 50);

    if (role === 'STUDENT') {
      let student = req.user.prismaId 
        ? await prisma.student.findUnique({ where: { id: req.user.prismaId } })
        : null;
      if (!student) student = await prisma.student.findUnique({ where: { email: req.user.email } });
      if (!student) return res.error('Student profile not found.', 404);

      const papers = await prisma.questionPaper.findMany({
        where: { studentId: student.id },
        orderBy: { createdAt: 'desc' },
        take: limit,
        include: { subject: true },
      });
      return res.success({ papers });
    }

    // Faculty/Admin: list papers created by them
    const papers = await prisma.questionPaper.findMany({
      where: { createdByUserId: req.user.id },
      orderBy: { createdAt: 'desc' },
      take: limit,
      include: { subject: true, student: true },
    });
    return res.success({ papers });
  } catch (err) {
    return res.error(err.message);
  }
};

export const getPaperById = async (req, res) => {
  try {
    const role = String(req.user.role || '').toUpperCase();
    const { id } = req.params;

    const paper = await prisma.questionPaper.findUnique({
      where: { id },
      include: {
        subject: true,
        student: true,
        items: { orderBy: { order: 'asc' }, include: { question: true } },
      },
    });

    if (!paper) return res.error('Paper not found.', 404);

    // Authorization:
    if (role === 'STUDENT') {
      let student = req.user.prismaId
        ? await prisma.student.findUnique({ where: { id: req.user.prismaId } })
        : null;
      if (!student) student = await prisma.student.findUnique({ where: { email: req.user.email } });
      if (!student) return res.error('Student profile not found.', 404);
      if (paper.studentId !== student.id) return res.error('Access denied.', 403);
    } else {
      if (paper.createdByUserId !== req.user.id && role !== 'ADMIN') return res.error('Access denied.', 403);
    }

    // Return in secure exam-ready JSON format
    return res.success({
      exam_metadata: {
        paper_id: paper.id,
        subject: paper.subject.subjectName,
        subject_code: paper.subject.subjectCode,
        total_marks: paper.totalMarks,
        exam_type: paper.examType,
        adaptive_enabled: paper.adaptiveEnabled,
        seed: paper.seed,
        status: paper.status,
        locked_at: paper.lockedAt,
        created_at: paper.createdAt,
      },
      questions: paper.items.map(it => ({
        id: it.questionId,
        type: it.question.questionType === 'SHORT_ANSWER' ? 'Short Answer' : it.question.questionType,
        difficulty: it.question.difficulty,
        bloom_level: it.question.bloomLevel,
        unit: it.question.unit,
        topic: it.question.topic,
        marks: it.marks,
        question_text: it.question.questionText,
      })),
    });
  } catch (err) {
    return res.error(err.message);
  }
};

export const deletePaperById = async (req, res) => {
  try {
    const role = String(req.user.role || '').toUpperCase();
    const { id } = req.params;

    const paper = await prisma.questionPaper.findUnique({ where: { id } });
    if (!paper) return res.error('Paper not found.', 404);

    if (role === 'STUDENT') {
      let student = req.user.prismaId
        ? await prisma.student.findUnique({ where: { id: req.user.prismaId } })
        : null;
      if (!student) student = await prisma.student.findUnique({ where: { email: req.user.email } });
      if (!student) return res.error('Student profile not found.', 404);
      if (paper.studentId !== student.id) return res.error('Access denied.', 403);
      if (paper.examType !== 'PRACTICE') return res.error('Students can only delete practice papers.', 403);
    } else {
      if (paper.createdByUserId !== req.user.id && role !== 'ADMIN') return res.error('Access denied.', 403);
    }

    await prisma.questionPaper.delete({ where: { id } });
    return res.success(null, 'Paper deleted successfully.');
  } catch (err) {
    return res.error(err.message);
  }
};

export const recordAttempts = async (req, res) => {
  try {
    const role = String(req.user.role || '').toUpperCase();
    if (role !== 'STUDENT') return res.error('Only students can record attempts.', 403);

    let student = req.user.prismaId
      ? await prisma.student.findUnique({ where: { id: req.user.prismaId } })
      : null;
    if (!student) student = await prisma.student.findUnique({ where: { email: req.user.email } });
    if (!student) return res.error('Student profile not found.', 404);

    const { paperId, attempts } = req.body;
    const questionIds = Array.from(new Set(attempts.map(a => a.questionId)));

    const questions = await prisma.question.findMany({
      where: { id: { in: questionIds } },
      select: { id: true, subjectId: true, topic: true },
    });
    const qMap = new Map(questions.map(q => [q.id, q]));

    for (const qid of questionIds) {
      if (!qMap.has(qid)) return res.error(`Question not found: ${qid}`, 404);
    }

    // Optional: validate paper ownership
    if (paperId) {
      const paper = await prisma.questionPaper.findUnique({ where: { id: paperId } });
      if (!paper) return res.error('Paper not found.', 404);
      if (paper.studentId !== student.id) return res.error('Access denied.', 403);
    }

    const grouped = new Map(); // key = `${subjectId}::${topic}`
    for (const a of attempts) {
      const q = qMap.get(a.questionId);
      const key = `${q.subjectId}::${q.topic}`;
      if (!grouped.has(key)) grouped.set(key, { subjectId: q.subjectId, topic: q.topic, n: 0, correct: 0, totalMs: 0, hasRt: 0 });
      const g = grouped.get(key);
      g.n += 1;
      if (a.isCorrect === true) g.correct += 1;
      if (Number.isFinite(a.responseTimeMs)) {
        g.totalMs += Number(a.responseTimeMs);
        g.hasRt += 1;
      }
    }

    await prisma.$transaction(async (tx) => {
      await tx.studentQuestionAttempt.createMany({
        data: attempts.map(a => ({
          studentId: student.id,
          questionId: a.questionId,
          paperId: paperId || null,
          isCorrect: a.isCorrect ?? null,
          responseTimeMs: Number.isFinite(a.responseTimeMs) ? Number(a.responseTimeMs) : null,
        })),
      });

      for (const g of grouped.values()) {
        const existing = await tx.studentTopicPerformance.findUnique({
          where: { studentId_subjectId_topic: { studentId: student.id, subjectId: g.subjectId, topic: g.topic } },
        });

        const addAttempts = g.n;
        const addCorrect = g.correct;
        const addAvgSec = g.hasRt ? (g.totalMs / g.hasRt) / 1000 : null;

        if (!existing) {
          const attemptCount = addAttempts;
          const correctCount = addCorrect;
          const accuracyPercentage = attemptCount ? (correctCount / attemptCount) * 100 : 0;
          const averageResponseTime = addAvgSec ?? 0;
          await tx.studentTopicPerformance.create({
            data: {
              studentId: student.id,
              subjectId: g.subjectId,
              topic: g.topic,
              attemptCount,
              correctCount,
              accuracyPercentage,
              averageResponseTime,
              weakFlag: accuracyPercentage < 50,
            }
          });
          continue;
        }

        const nextAttemptCount = (existing.attemptCount || 0) + addAttempts;
        const nextCorrectCount = (existing.correctCount || 0) + addCorrect;
        const nextAccuracy = nextAttemptCount ? (nextCorrectCount / nextAttemptCount) * 100 : 0;

        let nextAvgResp = existing.averageResponseTime || 0;
        if (addAvgSec != null) {
          // Weighted by attempts with response time (fallback to attempts)
          const oldWeight = Math.max(1, existing.attemptCount || 0);
          const newWeight = Math.max(1, addAttempts);
          nextAvgResp = ((nextAvgResp * oldWeight) + (addAvgSec * newWeight)) / (oldWeight + newWeight);
        }

        await tx.studentTopicPerformance.update({
          where: { id: existing.id },
          data: {
            attemptCount: nextAttemptCount,
            correctCount: nextCorrectCount,
            accuracyPercentage: nextAccuracy,
            averageResponseTime: nextAvgResp,
            weakFlag: nextAccuracy < 50,
          }
        });
      }
    });

    return res.success({ recorded: attempts.length, topicsUpdated: grouped.size }, 'Attempts recorded.');
  } catch (err) {
    return res.error(err.message, 400);
  }
};

